[project]
name = "drf-mock-response"
version = "0.1.0"
description = "Reusable mock response views for Django REST Framework"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "djangorestframework>=3.14",
    "setuptools>=80.9.0",
]
